ALTER TABLE address_level ENABLE ROW LEVEL SECURITY;
ALTER TABLE catchment ENABLE ROW LEVEL SECURITY;
ALTER TABLE catchment_address_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklist ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklist_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE concept ENABLE ROW LEVEL SECURITY;
ALTER TABLE concept_answer ENABLE ROW LEVEL SECURITY;
ALTER TABLE encounter ENABLE ROW LEVEL SECURITY;
ALTER TABLE encounter_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE form ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_element ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_element_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE individual ENABLE ROW LEVEL SECURITY;
ALTER TABLE program ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_encounter ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_enrolment ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_outcome ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;


CREATE POLICY address_level_user ON address_level USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY catchment_user ON catchment USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY catchment_address_mapping_user ON catchment_address_mapping USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY checklist_user ON checklist USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY checklist_item_user ON checklist_item USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY concept_user ON concept USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY concept_answer_user ON concept_answer USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY encounter_user ON encounter USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY encounter_type_user ON encounter_type USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY form_user ON form USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY form_element_user ON form_element USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY form_element_group_user ON form_element_group USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY form_mapping_user ON form_mapping USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY individual_user ON individual USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY program_user ON program USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY program_encounter_user ON program_encounter USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY program_enrolment_user ON program_enrolment USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY program_outcome_user ON program_outcome USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));
CREATE POLICY users_user ON users USING (organisation_id in (select id from organisation where db_user in ('openchs', current_user)))WITH CHECK (organisation_id in (select id from organisation where db_user in ('openchs', current_user)));