call update_audit_columns_from_audit_table('program_encounter');
commit;
call update_audit_columns_from_audit_table('program_enrolment');
commit;
call update_audit_columns_from_audit_table('address_level');
commit;
call update_audit_columns_from_audit_table('encounter');
commit;
call update_audit_columns_from_audit_table('gender');
commit;
call update_audit_columns_from_audit_table('individual');
commit;
call update_audit_columns_from_audit_table('operational_encounter_type');
commit;
call update_audit_columns_from_audit_table('address_level_type');
commit;
call update_audit_columns_from_audit_table('catchment');
commit;
call update_audit_columns_from_audit_table('program');
commit;
call update_audit_columns_from_audit_table('report_card');
commit;
call update_audit_columns_from_audit_table('form');
commit;
call update_audit_columns_from_audit_table('form_mapping');
commit;
call update_audit_columns_from_audit_table('operational_program');
commit;
call update_audit_columns_from_audit_table('concept');
commit;
call update_audit_columns_from_audit_table('concept_answer');
commit;
call update_audit_columns_from_audit_table('form_element');
commit;
call update_audit_columns_from_audit_table('form_element_group');
commit;
call update_audit_columns_from_audit_table('encounter_type');
commit;
call update_audit_columns_from_audit_table('dashboard');
commit;
call update_audit_columns_from_audit_table('dashboard_card_mapping');
commit;
call update_audit_columns_from_audit_table('operational_subject_type');
commit;
call update_audit_columns_from_audit_table('checklist');
commit;
call update_audit_columns_from_audit_table('checklist_detail');
commit;
call update_audit_columns_from_audit_table('checklist_item');
commit;
call update_audit_columns_from_audit_table('checklist_item_detail');
commit;
call update_audit_columns_from_audit_table('location_location_mapping');
commit;
call update_audit_columns_from_audit_table('facility');
commit;
call update_audit_columns_from_audit_table('group_privilege');
commit;
call update_audit_columns_from_audit_table('group_role');
commit;
call update_audit_columns_from_audit_table('group_subject');
commit;
call update_audit_columns_from_audit_table('groups');
commit;
call update_audit_columns_from_audit_table('identifier_assignment');
commit;
call update_audit_columns_from_audit_table('identifier_source');
commit;
call update_audit_columns_from_audit_table('identifier_user_assignment');
commit;
call update_audit_columns_from_audit_table('individual_relation');
commit;
call update_audit_columns_from_audit_table('individual_relationship');
commit;
call update_audit_columns_from_audit_table('individual_relationship_type');
commit;
call update_audit_columns_from_audit_table('individual_relation_gender_mapping');
commit;
call update_audit_columns_from_audit_table('individual_relative');
commit;
call update_audit_columns_from_audit_table('news');
commit;
call update_audit_columns_from_audit_table('comment');
commit;
call update_audit_columns_from_audit_table('msg91_config');
commit;
call update_audit_columns_from_audit_table('entity_approval_status');
commit;
call update_audit_columns_from_audit_table('group_dashboard');
commit;
call update_audit_columns_from_audit_table('dashboard_section');
commit;
call update_audit_columns_from_audit_table('dashboard_section_card_mapping');
commit;
call update_audit_columns_from_audit_table('subject_type');
commit;
call update_audit_columns_from_audit_table('non_applicable_form_element');
commit;
call update_audit_columns_from_audit_table('organisation_config');
commit;
call update_audit_columns_from_audit_table('platform_translation');
commit;
call update_audit_columns_from_audit_table('program_organisation_config');
commit;
call update_audit_columns_from_audit_table('program_outcome');
commit;
call update_audit_columns_from_audit_table('rule');
commit;
call update_audit_columns_from_audit_table('rule_dependency');
commit;
call update_audit_columns_from_audit_table('rule_failure_log');
commit;
call update_audit_columns_from_audit_table('rule_failure_telemetry');
commit;
call update_audit_columns_from_audit_table('translation');
commit;
call update_audit_columns_from_audit_table('user_facility_mapping');
commit;
call update_audit_columns_from_audit_table('user_group');
commit;
call update_audit_columns_from_audit_table('video');
commit;
call update_audit_columns_from_audit_table('comment_thread');
commit;
