ALTER TABLE form DROP CONSTRAINT IF EXISTS form_uuid_key;
ALTER TABLE form ADD CONSTRAINT form_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE form_element_group DROP CONSTRAINT IF EXISTS form_element_group_uuid_key;
ALTER TABLE form_element_group ADD CONSTRAINT form_element_group_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE form_element DROP CONSTRAINT IF EXISTS form_element_uuid_key;
ALTER TABLE form_element ADD CONSTRAINT form_element_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE concept DROP CONSTRAINT IF EXISTS concept_uuid_key;
ALTER TABLE concept ADD CONSTRAINT concept_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE concept_answer DROP CONSTRAINT IF EXISTS concept_answer_uuid_key;
ALTER TABLE concept_answer ADD CONSTRAINT concept_answer_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE form_mapping DROP CONSTRAINT IF EXISTS form_mapping_uuid_key;
ALTER TABLE form_mapping ADD CONSTRAINT form_mapping_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE checklist_detail DROP CONSTRAINT IF EXISTS checklist_detail_uuid_key;
ALTER TABLE checklist_detail ADD CONSTRAINT checklist_detail_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE catchment DROP CONSTRAINT IF EXISTS catchment_uuid_key;
ALTER TABLE catchment ADD CONSTRAINT catchment_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE address_level DROP CONSTRAINT IF EXISTS address_level_uuid_key;
ALTER TABLE address_level ADD CONSTRAINT address_level_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE program DROP CONSTRAINT IF EXISTS program_uuid_key;
ALTER TABLE program ADD CONSTRAINT program_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE gender DROP CONSTRAINT IF EXISTS gender_uuid_key;
ALTER TABLE gender ADD CONSTRAINT gender_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE encounter_type DROP CONSTRAINT IF EXISTS encounter_type_uuid_key;
ALTER TABLE encounter_type ADD CONSTRAINT encounter_type_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE operational_subject_type DROP CONSTRAINT IF EXISTS operational_subject_type_uuid_key;
ALTER TABLE operational_subject_type ADD CONSTRAINT operational_subject_type_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE video DROP CONSTRAINT IF EXISTS video_uuid_key;
ALTER TABLE video ADD CONSTRAINT video_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE identifier_source DROP CONSTRAINT IF EXISTS identifier_source_uuid_key;
ALTER TABLE identifier_source ADD CONSTRAINT identifier_source_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE identifier_user_assignment DROP CONSTRAINT IF EXISTS identifier_user_assignment_uuid_key;
ALTER TABLE identifier_user_assignment ADD CONSTRAINT identifier_user_assignment_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE translation ADD CONSTRAINT translation_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALter TABLE organisation_config ADD CONSTRAINT organisation_config_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_uuid_key;
ALTER TABLE users ADD CONSTRAINT users_uuid_org_id_key UNIQUE (uuid, organisation_id);
ALTER TABLE rule DROP CONSTRAINT IF EXISTS rule_uuid_key;
ALTER TABLE rule ADD CONSTRAINT rule_uuid_org_id_key UNIQUE (uuid, organisation_id);
