# NOT USED AS OF NOW

# FROM postgres:9.5.2

# RUN apt-get update
# RUN apt-get install -yq sudo
# USER postgres
# RUN pg_createcluster 9.5 main --start
# RUN sudo pg_ctlcluster 9.5 main status
# RUN sudo /etc/init.d/postgresql status
# && sudo -u postgres createdb openchs