CREATE OR REPLACE FUNCTION concept_uuid(TEXT)
  RETURNS TEXT
AS 'SELECT uuid
    FROM concept
    WHERE name = $1;'
LANGUAGE SQL
IMMUTABLE
RETURNS NULL ON NULL INPUT;

CREATE OR REPLACE FUNCTION text_obs(ANYELEMENT, TEXT)
  RETURNS TEXT
AS 'SELECT $1.observations ->> concept_uuid($2);'
LANGUAGE SQL
IMMUTABLE
RETURNS NULL ON NULL INPUT;

CREATE OR REPLACE FUNCTION numeric_obs(ANYELEMENT, TEXT)
  RETURNS NUMERIC AS $$
DECLARE obs NUMERIC;
BEGIN
  SELECT $1.observations ->> concept_uuid($2)
  INTO obs;
  RETURN obs;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION date_obs(ANYELEMENT, TEXT)
  RETURNS TIMESTAMP AS $$
DECLARE obs TIMESTAMP;
BEGIN
  SELECT $1.observations ->> concept_uuid($2)
  INTO obs;
  RETURN obs;
END;
$$ LANGUAGE plpgsql;