drop table health_metadata_version;

ALTER TABLE address_level ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE catchment ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE checklist ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE form ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE gender ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE operational_encounter_type ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE operational_program ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE organisation ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE program ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE program_encounter ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE program_organisation_config ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE program_outcome ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE rule_dependency ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE;